from research_and_analyst.prompt_library.prompts import (
    ANALYST_CREATION_PROMPT,
    INTERVIEW_QUESTION_PROMPT,
    SEARCH_QUERY_PROMPT,
    ANSWER_PROMPT,
    SECTION_WRITER_PROMPT,
    REPORT_WRITER_PROMPT,
    INTRODUCTION_PROMPT,
    CONCLUSION_PROMPT,
)
